**Задание 1.  Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.**

In [1]:
import numpy as np

In [2]:
# Футболисты
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [3]:
# Хоккеисты
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [4]:
# Штангисты
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [5]:
n1 = len(y1)
n1

8

In [6]:
n2 = len(y2)
n2

9

In [7]:
n3 = len(y3)
n3

11

In [8]:
n = n1 + n2 + n3
n

28

In [9]:
k = 3 # количество групп

In [10]:
y1_mean = np.mean(y1)
y1_mean

179.125

In [11]:
y2_mean = np.mean(y2)
y2_mean

178.66666666666666

In [12]:
y3_mean = np.mean(y3)
y3_mean

172.72727272727272

Средний рост спортсменов различается. Установим, что это отличие статистически значимо. Для этого сначала соберем все значения роста в один массив:

In [13]:
y_all = np.concatenate([y1, y2, y3])
y_all

array([173, 175, 180, 178, 177, 185, 183, 182, 177, 179, 180, 188, 177,
       172, 171, 184, 180, 172, 173, 169, 177, 166, 180, 178, 177, 172,
       166, 170])

Найдем среднее значение роста спортсменов по всем значениям:

In [14]:
y_mean = np.mean(y_all)
y_mean

176.46428571428572

Найдем $S^2$ — сумму квадратов отклонений наблюдений от общего среднего:

In [15]:
s2 = np.sum((y_all - y_mean)**2)
s2

830.9642857142854

Найдем $S^2_F$ - сумму квадратов отклонений средних групповых значений от общего среднего:

In [16]:
s2_f = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3
s2_f

253.9074675324678

Найдем $S^2_{ост}$ — остаточную сумму квадратов отклонений:

In [17]:
s2_res = np.sum((y1 - y1_mean)**2) + np.sum((y2 - y2_mean)**2) + np.sum((y3 - y3_mean)**2)
s2_res

577.0568181818182

Удостоверимся, что соблюдается равенство $S^2 = S_F^2 + S_{ост}^2$:

In [18]:
s2_f + s2_res

830.964285714286

In [19]:
s2

830.9642857142854

Найдем общую дисперсию:

In [20]:
sigma2_general = s2 / (n - 1)
sigma2_general

30.776455026455015

Найдем факторную дисперсию:

In [21]:
sigma2_f = s2_f / (k - 1)
sigma2_f

126.9537337662339

Найдем остаточную дисперсию:

In [22]:
sigma2_res = s2_res / (n - k)
sigma2_res

23.08227272727273

Вычислим $F_H$:

In [23]:
F_h = sigma2_f / sigma2_res
F_h

5.500053450812598

Найдем значение $F_{крит}$ в таблице критических точек распределения Фишера-Снедекора для заданного уровня значимости $\alpha = 0.05$ и двух степеней свободы: 

$df_{межд} = k - 1 = 3 - 1 = 2$ и $df_{внутр} = n - k = 28 - 3 = 25$.

Для данных значений $F_{крит}$ лежит между значениями $3.40$ и $3.37$.  Так как $F_H > F_{крит}$, различие роста в трех группах статистически значимо.

**с помощью пакета scipy**

In [24]:
from scipy import stats

In [25]:
stats.f_oneway(y1,y2,y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)